top:

.PHONY: clean
clean:
	make -C ActoraStack clean
	make -C BRAMStack clean
	make -C CPU clean
	make -C FirstHot clean
	make -C MemAddr clean
	make -C RandomCheck clean
	make -C Sorter clean
	make -C Sums clean
	make -C Sums_Parallel clean
	make -C Synthesizable clean

